Repository ERB-2023/downtalk, pull requests merged in 2023-01, with the labels that each got.

#28 Feat: login
  apps/back/package.json
  apps/back/src/auth/auth.controller.ts
  apps/back/src/auth/auth.module.ts
  apps/back/src/auth/auth.service.ts
  yarn.lock
Labels: Feat, :postbox: Server

#32 Feat: Google auth
  apps/back/package.json
  apps/back/src/app.module.ts
  apps/back/src/auth/auth.controller.spec.ts
  apps/back/src/auth/auth.controller.ts
  apps/back/src/auth/auth.module.ts
  apps/back/src/auth/auth.service.spec.ts
  apps/back/src/auth/auth.service.ts
  apps/back/src/auth/google.startegy.ts
  yarn.lock
Labels: Feat, :postbox: Server

#33 Chore: Docker setting
  .dockerignore
  apps/back/api.Dockerfile
  apps/back/chat.Dockerfile
  apps/back/src/chat/chat.gateway.ts
  apps/back/src/main.ts
  apps/front/Dockerfile
  docker-compose.yml
Labels: Feat, Chore, :postbox: Server

#34 Chore: TypeOrm (Feat: Entity - User,Friend)
  apps/back/package.json
  apps/back/src/app.module.ts
  apps/back/src/common/enum/friend.enum.ts
  apps/back/src/database/database.module.ts
  apps/back/src/database/database.providers.ts
  apps/back/src/database/entity/friend.entity.ts
  apps/back/src/database/entity/user.entity.ts
  apps/back/src/database/providers/friend.provider.ts
  apps/back/src/database/providers/user.provider.ts
  yarn.lock
Labels: Feat, Chore, :postbox: Server

#37 Feat: HTTP Exception Filter
  apps/back/src/app.module.ts
  apps/back/src/app.service.ts
  apps/back/src/common/filter/exception.filter.ts
Labels: Feat, :postbox: Server

#36 Feat: Module(User,Friend)
  apps/back/src/app.module.ts
  apps/back/src/friend/friend.controller.spec.ts
  apps/back/src/friend/friend.controller.ts
  apps/back/src/friend/friend.module.ts
  apps/back/src/friend/friend.service.spec.ts
  apps/back/src/friend/friend.service.ts
  apps/back/src/user/user.controller.spec.ts
  apps/back/src/user/user.controller.ts
  apps/back/src/user/user.module.ts
  apps/back/src/user/user.service.spec.ts
  apps/back/src/user/user.service.ts
Labels: Feat, :postbox: Server

#35 Feat: Api Formatter
  apps/back/src/app.module.ts
  apps/back/src/common/interceptor/response.interceptor.ts
  apps/back/src/common/interface/response.interface.ts
Labels: Feat, :postbox: Server

#38 Feat: API, search User
  .vscode/PULL_REQUEST_TEMPLATE/feat_template.md
  .vscode/PULL_REQUEST_TEMPLATE/test_template.md
  apps/back/src/user/user.controller.spec.ts
  apps/back/src/user/user.controller.ts
  apps/back/src/user/user.module.ts
  apps/back/src/user/user.service.spec.ts
  apps/back/src/user/user.service.ts
Labels: Docs, :bulb: Client, :postbox: Server

#45 docker-compose setting
  .gitignore
  apps/back/package.json
  apps/back/src/app.module.ts
  apps/back/src/database/database.providers.ts
  docker-compose.yml
  docker_run.sh
  package-lock.json
  yarn.lock
Labels: Feat, :postbox: Server

#40 [Feat] Add friend
  apps/back/src/common/exception/friend.exception.ts
  apps/back/src/common/exception/user.exception.ts
  apps/back/src/friend/friend.controller.spec.ts
  apps/back/src/friend/friend.controller.ts
  apps/back/src/friend/friend.module.ts
  apps/back/src/friend/friend.service.spec.ts
  apps/back/src/friend/friend.service.ts
Labels: Feat, :postbox: Server

#39 [Feat] Get friend
  apps/back/src/friend/friend.controller.spec.ts
  apps/back/src/friend/friend.controller.ts
  apps/back/src/friend/friend.service.spec.ts
  apps/back/src/friend/friend.service.ts
Labels: Feat, :postbox: Server

#46 [Feat] Entity, Chat room
  apps/back/src/database/entity/chat-room.entity.ts
  apps/back/src/database/entity/user.entity.ts
  yarn.lock
Labels: Feat, :postbox: Server

#42 [feat] 홈 화면 작업 (#41)
  apps/front/package.json
  apps/front/public/images/favicon.ico
  apps/front/public/images/google-logo.svg
  apps/front/src/components/PageHead/index.tsx
  apps/front/src/components/home/index.module.scss
  apps/front/src/components/home/index.tsx
  apps/front/src/lottie/main-chatting.json
  apps/front/src/pages/_app.tsx
  apps/front/src/pages/exchange/index.tsx
  apps/front/src/pages/home/index.tsx
  apps/front/src/pages/index.tsx
  apps/front/src/pages/signin/index.tsx
  apps/front/src/styles/Home.module.scss
  apps/front/src/styles/global.scss
  packages/eslint-config-custom/index.js
  yarn.lock
Labels: Feat, :bulb: Client

#49 [Modify] Backend Test Case
  apps/back/package.json
  apps/back/src/app.service.ts
  apps/back/src/friend/friend.controller.spec.ts
  apps/back/src/friend/friend.service.spec.ts
  apps/back/src/user/user.controller.spec.ts
  apps/back/src/user/user.service.spec.ts
  yarn.lock
Labels: Fix, Modify, :postbox: Server

#47 [feat] 구글 간편 로그인 버튼 구현
  apps/front/next.config.js
  apps/front/package.json
  apps/front/src/pages/_app.tsx
  apps/front/src/pages/signin/index.tsx
  yarn.lock
Labels: Feat, :bulb: Client

#57 edit sso button && env setting
  apps/front/next.config.js
  apps/front/src/components/home/index.module.scss
  apps/front/src/components/home/index.tsx
  apps/front/src/data/google.tsx
  apps/front/src/pages/_app.tsx
  apps/front/src/pages/signin/index.tsx
Labels: Modify, :bulb: Client

#54 [Feat] chatting (socket.io)
  apps/back/src/chat/chat.gateway.ts
Labels: Feat, Docs, :postbox: Server

#55 [Feat] MongoDB
  apps/back/package.json
  apps/back/src/database/database.module.ts
  apps/back/src/database/database.providers.ts
  apps/back/src/database/schema/chat-log.schema.ts
  docker-compose.yml
  yarn.lock
Labels: Feat, Chore, :postbox: Server

#51 [Refactor] backend test
  apps/back/src/database/entity/chat-room.entity.ts
  apps/back/src/database/entity/friend.entity.ts
  apps/back/src/friend/friend.controller.spec.ts
  apps/back/src/friend/friend.controller.ts
  apps/back/src/friend/friend.module.ts
  apps/back/src/friend/friend.service.spec.ts
  apps/back/src/friend/friend.service.ts
  apps/back/src/user/user.controller.spec.ts
  apps/back/src/user/user.module.ts
  apps/back/src/user/user.service.spec.ts
  apps/back/src/user/user.service.ts
  apps/back/test/user.e2e-spec.ts
Labels: Fix, Refactor, :postbox: Server
