Repository ERB-2023/downtalk, pull requests merged in 2023-02, with the labels that each got.

#53 [Refactor] Chat, add host invitee
  apps/back/package.json
  apps/back/src/chat/chat.controller.spec.ts
  apps/back/src/chat/chat.controller.ts
  apps/back/src/chat/chat.module.ts
  apps/back/src/chat/chat.service.ts
  apps/back/src/chat/dto/create-room.dto.ts
  apps/back/src/common/enum/chat.enum.ts
  apps/back/src/database/entity/chat-room.entity.ts
  apps/back/src/database/entity/user-chat-room.entity.ts
  apps/back/src/database/entity/user.entity.ts
  apps/back/src/database/providers/chat-room.provider.ts
  apps/back/src/database/providers/user-chat-room.provider.ts
  yarn.lock
Labels: Feat, Refactor, :postbox: Server

#50 [Feat] Chat rooms API
  apps/back/src/chat/dto/create-room.dto.ts
Labels: Feat, :postbox: Server

#56 google-login-working
  apps/back/package.json
  apps/back/src/app.module.ts
  apps/back/src/auth/auth.controller.ts
  apps/back/src/auth/auth.module.ts
  apps/back/src/auth/auth.service.ts
  apps/back/src/common/dto/googleUserinfoDto.ts
  apps/back/src/common/dto/loginDto.ts
  apps/back/src/common/exception/auth.exception.ts
  apps/back/src/common/filter/exception.filter.ts
  apps/back/src/database/entity/user.entity.ts
  docker-compose.yml
  docker_run.sh
  local_run.sh
  yarn.lock
Labels: Feat, Modify, :postbox: Server

#66 docker-compose-error-fix
  apps/back/src/database/database.providers.ts
  docker-compose.yml
  docker_run.sh
  local_run.sh
Labels: Fix, Modify, :postbox: Server

#69 [Fix] Auth, Chat test compile error
  apps/back/src/auth/auth.controller.spec.ts
  apps/back/src/auth/auth.service.spec.ts
  apps/back/src/chat/chat.controller.spec.ts
Labels: Fix, Test, :postbox: Server

#64 [Feat] connect login api with google button
  apps/front/src/api/index.tsx
  apps/front/src/components/home/index.tsx
Labels: Feat, :bulb: Client

#71 [Feat] 환경설정 페이지 퍼블리싱
  apps/front/public/images/right_icon.svg
  apps/front/src/components/Settings/index.module.scss
  apps/front/src/components/Settings/index.tsx
  apps/front/src/data/settingsList.tsx
  apps/front/src/pages/profile/index.tsx
  apps/front/src/pages/settings/index.tsx
Labels: Feat, :bulb: Client

#67 [Feat] API, delete friend
  apps/back/src/database/entity/friend.entity.ts
  apps/back/src/database/entity/user.entity.ts
  apps/back/src/friend/friend.controller.spec.ts
  apps/back/src/friend/friend.controller.ts
  apps/back/src/friend/friend.exception.ts
  apps/back/src/friend/friend.service.spec.ts
  apps/back/src/friend/friend.service.ts
Labels: Feat, Test, Modify, :postbox: Server

#72 Jwt authentication logic change
  apps/back/package.json
  apps/back/src/auth/auth.controller.ts
  apps/back/src/auth/auth.service.ts
  apps/back/src/auth/auth.startegy.ts
  apps/back/src/database/entity/user.entity.ts
  docker-compose.yml
  local_run.sh
  yarn.lock
Labels: Feat, Modify, :postbox: Server
